# Generated by Django 6.0.1 on 2026-04-01 06:20

from django.db import migrations


def update_post_status(apps, schema_editor):
    """Update all existing posts to PUBLISHED status"""
    Post = apps.get_model('blog', 'Post')
    Post.objects.all().update(status='PB')


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.RunPython(update_post_status),
    ]
