# Generated by Django 6.0.1 on 2026-04-08 07:03
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_update_post_status'),
    ]

    operations = [
        TrigramExtension()
    ]
