# Generated by Django 6.0.2 on 2026-03-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('-age',)},
        ),
        migrations.AddField(
            model_name='student',
            name='dept',
            field=models.CharField(default='CSE', max_length=100),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['-age'], name='studentApp__age_00f23a_idx'),
        ),
    ]
